from typing import Protocol
import uuid
from ..contracts.connectors import ConnectorDTO

class IConnectorStore(Protocol):
    async def get_by_name(self, name: str) -> ConnectorDTO | None: ...
    async def get_by_id(self, connector_id: uuid.UUID) -> ConnectorDTO | None: ...
    async def get_by_ids(self, connector_ids: list[uuid.UUID]) -> list[ConnectorDTO]: ...