# FROM python:3.12.4-alpine
FROM python:3.13.7-slim-bookworm

WORKDIR /app/

COPY ./requirements.txt /app/requirements.txt

RUN apt install postgresql-server-dev-all

RUN python -m pip install --upgrade pip

RUN python -m pip install --no-cache-dir --ignore-requires-python -r /app/requirements.txt

COPY ./app /app/

CMD ["fastapi", "run", "main.py", "--port", "8000"]