# syntax=docker/dockerfile:1
FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY langbridge/requirements-worker.txt ./requirements.txt

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY langbridge /app/langbridge
COPY pyproject.toml /app/pyproject.toml

CMD ["python", "-m", "langbridge.apps.worker.langbridge_worker.main"]
